version: 2.1
#orbs:
  #sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - init
      - android-build-and-test:
          #context: SonarCloud
          requires: 
            - init
      - macos-build-and-test:
          requires: 
            - init
jobs:
  init:
    working_directory: ~/DeploymentPipeline
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
	  paths:
            - node_modules

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/DeploymentPipeline
          paths:
            - node_modules

  android-build-and-test:
    working_directory: ~/DeploymentPipeline/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout:
          path: ~/DeploymentPipeline
      - attach_workspace:
          at: ~/DeploymentPipeline
      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install && bundle update

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: fastlane tests
          command: |
            chmod +x ./gradlew
            bundle exec fastlane test
      - run:
          name: fastlane build
          command: fastlane build
            
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          
  macos-build-and-test:
    working_directory: ~/DeploymentPipeline
    macos:
      xcode: 11.3.0
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
          
      - restore_cache:
          key: 1-gems-{{ checksum "ios/Gemfile.lock" }}

      - run: 
          command: bundle install && bundle update
          working_directory: ios

      - save_cache:
          key: 1-gems-{{ checksum "ios/Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Fastlane
          command: bundle exec fastlane test
          working_directory: ios      
      
      - store_artifacts:
          path: output
          
      - store_test_results:
          path: output/scan
