# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all tests"
  lane :test do
    gradle(task: 'clean')
    gradle(task: 'test')
  end
  
  desc 'Build the Android application.'
   lane :build do
    build_number=number_of_commits()
    gradle(
      task: 'assemble', 
      build_type: 'Release', 
      properties: {
        "VERSION_CODE" => build_number,
        "ANDROID_SDK_ROOT" => "/var/lib/jenkins/tools",
        "android.injected.signing.store.file" => "/home/ec2-user/keystore.jks",
        "android.injected.signing.store.password" => "X7CKBHA5wChxgWA0mwnz",
        "android.injected.signing.key.alias" => "key0",
        "android.injected.signing.key.password" => "GzT4Q1rtbWiJAgKfDOIE"
        })
   end

  desc "Submit a new Alpha Build"
  lane :alpha do
    upload_to_play_store(track: 'internal')
  end

  desc "Submit a new Beta Build"
  lane :beta do
    upload_to_play_store(track: 'alpha')
  end
end
